### ISSUE TITLE
Разработка

### ISSUE THREAD

**Issue by Simplas920** [osben/Simpla#29]
[Здесь](https://www.nulled.cc/threads/300189/page-2#post-2942980) пишут, что форк развиваться больше не будет. Можно доверять?

**Comment by osben** [comment]
Странно, я ничего такого не говорил кажется. Но, очевидно что у меня времени не было и нету особо заниматься. Если микро улучшение будут в PR то без проблем прийму их

**Comment by pulse-studio** [comment]
"на заборе тоже написано".
