### ISSUE TITLE
С репозитория Пикусова

### ISSUE THREAD

**Issue by Simplas920** [osben/Simpla#30]
В репозитории Пикусова есть некоторые доработки:

- [ ] [политика безопасности для GitHub](https://github.com/pikusov/Simpla/pull/196)
- [ ] [продление лицензии](https://github.com/pikusov/Simpla/pull/193)
- [ ] [исправление орфографических ошибок](https://github.com/pikusov/Simpla/pull/189)
- [ ] [удаление лишней проверки](https://github.com/pikusov/Simpla/pull/187)

Также есть некоторые проблемы (решение может быть тривиальным):
- [ ] **[проверка лицензии](https://github.com/pikusov/Simpla/issues/188)** — желательно удалить из-за появления мошенников
- [ ] [повторение проверки лицензии](https://github.com/pikusov/Simpla/issues/200)
- [ ] [дебаг-лицензия](https://github.com/pikusov/Simpla/issues/198)
- XSS
- - [ ] [имя](https://github.com/pikusov/Simpla/issues/173)
- - [ ] [лицензия](https://github.com/pikusov/Simpla/issues/194)

**Comment by osben** [comment]
Только PR, то есть полезную нагрузку готов обработать. Извините

**Comment by Simplas920** [comment]
Так пусть висит здесь, чтобы другие знали, что нужно делать.
