### ISSUE TITLE
Дополнительные репозитории

### ISSUE THREAD

**Issue by Simplas920** [osben/Simpla#37]
Желательно создать дополнительные репозитории для установщика (install.php, на форуме есть версия для PHP7) и демо-файлов для товаров из simpla.sql, которые есть в оригинальном архиве на сайте.

**Comment by osben** [comment]
буду раз PR

**Comment by Simplas920** [comment]
@osben PR здесь недостаточно. Репозитории от Вашего имени никто не создаст.

**Comment by osben** [comment]
почему же, мне кажется было было круто в корне иметь install.php которые будет открываться когда нету config/config.php и будет предлагать пройти установку и т.д. 
согласны ?

**Comment by Simplas920** [comment]
Ок, сейчас сделаю установщик под PHP7 в PR
