### ISSUE TITLE
Изменить термин «Лицензия» → «Лицензионный ключ»

### ISSUE THREAD

**Issue by Simplas920** [osben/Simpla#47]
В Simpla CMS везде используется термин юридический «лицензия», как для самой лицензии, так и для ключа и записи домена на сайте simplacms.ru. Тем не менее, использование кейгена/взлом сайта с добавлением своего домена права на использование CMS не даёт.

Рекомендую заменить на «лицензионный ключ». С кнопкой «проверить лицензию» также нужно что-то сделать (на сайте нет HTTPS и его время от времени атакуют хакеры).

PR нет — боюсь, что простая замена может нарушить обратную совместимость.

**Comment by osben** [comment]
Скажи, где я могу тебя заблокировать ?

**Comment by Simplas920** [comment]
> Скажи, где я могу тебя заблокировать ?

@osben, [здесь](https://help.github.com/en/github/building-a-strong-community/blocking-a-user-from-your-personal-account).
